imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            action_level: notice
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: [!event, !translation]
            level: info
        console:
            type:   console
            action_level: notice
            channels: [!event, !translation, !doctrine ]
            level: info

#swiftmailer:
#    delivery_address: me@example.com
