security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:  [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, in_memory]
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user: {password: "$2y$13$mO/BvP3/lkbELN3Bpfr.cetrDQVY9NHErw5Cytajxzcj.vR7KoVgW", roles: ['ROLE_USER'] }
                    admin: { password: "$2y$13$j78ybwNIrRvOh5JX8.YXD.7ZB9N5KN9sQceQd25PIkN2YiWzf53eq", roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: "$2y$13$QvWmvERMqYwEebPiaxrns.gH6rlMIFDuwNrmQYQYdiEEYHljju8vC", roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
            logout: ~
            anonymous: ~
            http_basic: ~


    access_control:
        #TODOS pueden ver el login
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        #ROL SUPER_ADMIN
        - { path: ^/easyadmin/, roles: [ROLE_SUPER_ADMIN] }
        - { path: ^/issue/, roles: [ROLE_SUPER_ADMIN] }
        - { path: ^/user/, roles: [ROLE_SUPER_ADMIN] }
        - { path: ^/change-password/*, role: [ROLE_USER] }
        - { path: ^/, roles: [ROLE_USER] }
