services:
  db_audit.event_subscriber:
    class: DbAuditBundle\EventSubscriber\AuditSubscriber
    arguments: ["@security.token_storage"]
    tags:
      - { name: doctrine.event_subscriber, connection: default }
